# Generated by Django 4.1 on 2022-09-28 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comments_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='item_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_auction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_auction', to='auctions.auctionlisting')),
                ('watchlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
