# Generated by Django 4.1 on 2022-09-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_item_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist_auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_auction', to='auctions.auctionlisting'),
        ),
    ]
