# Generated by Django 4.1 on 2022-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_watchlist_watchlist_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist_auction',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_auction',
            field=models.ManyToManyField(blank=True, related_name='watch_auction', to='auctions.auctionlisting'),
        ),
    ]
